[project]
name = "openmlxmodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mlx>=0.27.1",
    "numpy>=2.3.1",
    "tiktoken>=0.9.0",
]
